<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from /home/matthew/buildkit/build/d7master/web/sites/default/files/civicrm/ext/firewall/xml/schema/CRM/Firewall/FirewallCsrfToken.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:78dd01eb060238086652f9f352639aa7)
 */

/**
 * Database access object for the FirewallCsrfToken entity.
 */
class CRM_Firewall_DAO_FirewallCsrfToken extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_firewall_csrf_token';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = FALSE;

  /**
   * Unique FirewallCsrfToken ID
   *
   * @var int
   */
  public $id;

  /**
   * When the token was created
   *
   * @var timestamp
   */
  public $created_date;

  /**
   * The CSRF token
   *
   * @var string
   */
  public $token;

  /**
   * Source of this CSRF token
   *
   * @var string
   */
  public $source;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_firewall_csrf_token';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   */
  public static function getEntityTitle() {
    return ts('Firewall Csrf Tokenses');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Firewall_ExtensionUtil::ts('Unique FirewallCsrfToken ID'),
          'required' => TRUE,
          'where' => 'civicrm_firewall_csrf_token.id',
          'table_name' => 'civicrm_firewall_csrf_token',
          'entity' => 'FirewallCsrfToken',
          'bao' => 'CRM_Firewall_DAO_FirewallCsrfToken',
          'localizable' => 0,
          'add' => NULL,
        ],
        'created_date' => [
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => CRM_Firewall_ExtensionUtil::ts('Created Date'),
          'description' => CRM_Firewall_ExtensionUtil::ts('When the token was created'),
          'required' => TRUE,
          'where' => 'civicrm_firewall_csrf_token.created_date',
          'default' => 'CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_firewall_csrf_token',
          'entity' => 'FirewallCsrfToken',
          'bao' => 'CRM_Firewall_DAO_FirewallCsrfToken',
          'localizable' => 0,
          'add' => NULL,
        ],
        'token' => [
          'name' => 'token',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Firewall_ExtensionUtil::ts('Token'),
          'description' => CRM_Firewall_ExtensionUtil::ts('The CSRF token'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_firewall_csrf_token.token',
          'table_name' => 'civicrm_firewall_csrf_token',
          'entity' => 'FirewallCsrfToken',
          'bao' => 'CRM_Firewall_DAO_FirewallCsrfToken',
          'localizable' => 0,
          'add' => NULL,
        ],
        'source' => [
          'name' => 'source',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Firewall_ExtensionUtil::ts('Source'),
          'description' => CRM_Firewall_ExtensionUtil::ts('Source of this CSRF token'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_firewall_csrf_token.source',
          'table_name' => 'civicrm_firewall_csrf_token',
          'entity' => 'FirewallCsrfToken',
          'bao' => 'CRM_Firewall_DAO_FirewallCsrfToken',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'firewall_csrf_tokens', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'firewall_csrf_tokens', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
