-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_firewall_ipaddress`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_firewall_ipaddress
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_firewall_ipaddress` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique FirewallIpaddress ID',
     `ip_address` varchar(255)    COMMENT 'IP address used',
     `access_date` timestamp NOT NULL  DEFAULT CURRENT_TIMESTAMP COMMENT 'When the IP address accessed',
     `event_type` varchar(64)    COMMENT 'The type of event that triggered this log',
     `source` varchar(255)    COMMENT 'Origin of this access request' 
,
        PRIMARY KEY (`id`)
 
 
 
)    ;

 
